test('should fail', () => {
    throw new Exception('failure!')
})